---
- hosts: dockerhost

  tasks:
    - name: stop existing containers
      command: docker stop regapp-server
      ignore_errors: yes

    - name: delete container
      command: docker rm regapp-server
      ignore_errors: yes

    - name: delete images 
      command: docker rmi subhadepp/regapp:latest
      ignore_errors: yes

    - name: create container
      command: docker run -d --name regapp-server -p 8082:8080 subhadepp/regapp:latest